#![allow(non_snake_case)]
#![allow(dead_code)]

pub mod acc2d;
pub mod acc2d_cyclic;
pub mod affine1d;
pub mod affine2d;
pub mod bit;
pub mod bit_2d;
pub mod bitset;
mod cfor;
mod chmax;
mod chmin;
pub mod comb;
pub mod comb_no_mod;
pub mod consts;
pub mod coordinate_compression;
pub mod crt;
mod debug;
mod debug2D;
pub mod dijkstra;
pub mod dual_segment_tree;
pub mod dynamic_segment_tree;
pub mod enum_pairs;
pub mod extmonoid;
pub mod extmonoid_mod;
pub mod factorize;
pub mod factorize_fast;
pub mod factors_all;
pub mod ford_fulkerson;
pub mod frac;
mod get;
pub mod grid;
pub mod indexedset;
pub mod lazy_segment_tree;
pub mod lca_doubling;
pub mod lcs;
pub mod lineartime_merging;
pub mod loop_detection;
pub mod loop_detection_fold;
pub mod matrix_exp;
pub mod mex_set;
pub mod miller_rabin_test;
pub mod modint;
pub mod modint_comb;
pub mod modint_for_rollinghash;
pub mod modint_traits;
pub mod monoid;
pub mod monoid_examples;
pub mod monoid_mod;
pub mod multiset;
pub mod multiset_splay_tree;
pub mod namori;
pub mod pollard_rho_algorithm;
pub mod powmod;
pub mod rolling_hash;
pub mod run_length;
pub mod scc;
pub mod segment_tree;
pub mod segment_tree_2d;
pub mod segment_tree_mutable;
pub mod segmented_sieve;
pub mod simple_graph;
pub mod sparse_table;
pub mod trie;
pub mod union_find;
pub mod vec2;
pub mod weighted_union_find;
pub mod yesno;
pub mod zigzag;
