name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cp-library-py/**"
      - "cp-library-rs/**"
  pull_request:
    branches:
      - main
    paths:
      - "cp-library-py/**"
      - "cp-library-rs/**"

jobs:
  rust-doc:
    runs-on: ubuntu-latest
    # needs: build
    defaults:
      run:
        working-directory: ./cp-library-rs
    steps:
      - uses: actions/checkout@v3
      - name: download KaTeX
        run: curl -O https://raw.githubusercontent.com/CAD97/katex-doc/master/katex.html
      - name: Run doc
        run: cargo rustdoc -- --html-in-header katex.html

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-rust
          path: "cp-library-rs/target/doc"
          compression-level: 0

  python-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cp-library-py/docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build docs
        run: sphinx-apidoc -f -o ./docs/source ../cp_library_py

      - name: Build html
        run: make html

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-python
          path: "cp_library_py/_build/html"
          compression-level: 0

  deploy:
    runs-on: ubuntu-latest
    needs: [rust-doc, python-doc]
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # Download the book's HTML artifact
      - uses: actions/download-artifact@v4

      # Delete artifacts
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            artifact-rust
            artifact-python

      - name: show files
        run: |
          ls -l
          ls artifact-rust

      - name: pages
        run: |
          mkdir pages

      # merge artifacts
      - name: Merge artifacts
        run: |
          mv artifact-rust/cp_library_rs pages/cp-library-rs
          mv artifact-python/html pages/cp-library-py

      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: pages

      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
