name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cp-library-py/**"
  pull_request:
    branches:
      - main
    paths:
      - "cp-library-py/**"

jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cp-library-py
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Run mypy
        run: uv run mypy src

      - name: Run test
        run: uv run python -m unittest discover -v
