# https://qiita.com/hystcs/items/e5712c43464acb4a414e
name: Rust CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cp-library-rs/**"
  pull_request:
    branches:
      - main
    paths:
      - "cp-library-rs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cp-library-rs
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads=8
